version: "3"

services:
    postgres:
        container_name: dashboard-postgres
        image: postgres
        env_file: 
            - ./.env
        ports:
            - 5432:5432
        networks:
            - database

networks:
    database: