version: "3"

services:
    api:
        container_name: api
        build: ./dashboard-server
        ports:
            - "3333:3333"
        env_file:
            - ./dashboard-server/.env-docker
        depends_on:
            - postgres
        networks:
            - database

    client:
        container_name: client
        build: ./dashboard-client
        ports:
            - "80:80"
        env_file:
            - ./dashboard-client/.env
        networks:
            - database
        links:
          - api

    postgres:
        image: postgres
        env_file: 
            - .env
        ports:
            - 5432:5432
        networks:
            - database

networks:
    database:
